// DON'T Forget to update sayitEngines in blockly.js (if you change this table)

const sayitOptions = {
    'browser':    { name: 'Browser',           mp3Required: true,  checkLength: true,  func: (typeof sayItBrowser    !== 'undefined') ? sayItBrowser    : null, server: true,  libs: ['fs', 'crypto', 'http'] },
    'mp24ftp':    { name: 'MediaPlayer24+FTP', mp3Required: true,  checkLength: true,  func: (typeof sayItMP24ftp    !== 'undefined') ? sayItMP24ftp    : null, server: false, libs: ['fs', 'crypto', 'http', 'jsftp'] },
    'mp24':       { name: 'MediaPlayer24',     mp3Required: false, checkLength: true,  func: (typeof sayItMP24       !== 'undefined') ? sayItMP24       : null, server: false, libs: ['fs', 'crypto', 'http'] },
    'system':     { name: 'System',            mp3Required: true,  checkLength: false, func: (typeof sayItSystem     !== 'undefined') ? sayItSystem     : null, server: false, libs: ['fs', 'crypto', 'http', 'child_process', 'os'] },
    'windows':    { name: 'Windows default',   mp3Required: false, checkLength: true,  func: (typeof sayItWindows    !== 'undefined') ? sayItWindows    : null, server: false, libs: ['fs', 'child_process'] },
    'sonos':      { name: 'Sonos',             mp3Required: true,  checkLength: true,  func: (typeof sayItSonos      !== 'undefined') ? sayItSonos      : null, server: true,  libs: ['fs', 'crypto', 'http'] },
    'heos':       { name: 'Heos',              mp3Required: true,  checkLength: true,  func: (typeof sayItHeos       !== 'undefined') ? sayItHeos       : null, server: true,  libs: ['fs', 'crypto', 'http'] },
    'lametric':   { name: 'LaMetric',          mp3Required: true,  checkLength: true,  func: (typeof sayItLaMetric   !== 'undefined') ? sayItLaMetric   : null, server: true,  libs: ['fs', 'crypto', 'http'] },
    'chromecast': { name: 'Chromecast',        mp3Required: true,  checkLength: true,  func: (typeof sayItChromecast !== 'undefined') ? sayItChromecast : null, server: true,  libs: ['fs', 'crypto', 'http'] },
    'mpd':        { name: 'MPD',               mp3Required: true,  checkLength: true,  func: (typeof sayItMpd        !== 'undefined') ? sayItMpd        : null, server: true,  libs: ['fs', 'crypto', 'http'] },
    'googleHome': { name: 'Google Home',       mp3Required: true,  checkLength: true,  func: (typeof sayItGoogleHome !== 'undefined') ? sayItGoogleHome : null, server: true,  libs: ['fs', 'crypto', 'http', 'castv2-client'] },
};

const sayitEngines = {
    'en':                           { name: 'Google - English',                              engine: 'google' },
    'de':                           { name: 'Google - Deutsch',                              engine: 'google' },
    'pl':                           { name: 'Google - Polski',                               engine: 'google' },
    'uk':                           { name: 'Google - Ukrainian',                            engine: 'google' },
    'ru':                           { name: 'Google - Русский',                              engine: 'google' },
    'it':                           { name: 'Google - Italiano',                             engine: 'google' },
    'pt':                           { name: 'Google - Português',                            engine: 'google' },
    'es':                           { name: 'Google - Espaniol',                             engine: 'google' },
    'fr':                           { name: 'Google - Français',                             engine: 'google' },
    'nl':                           { name: 'Google - Nederlands',                           engine: 'google' },
    'zh-CN':                        { name: 'Google - 简体中文',                              engine: 'google' },

    'no':                           { name: 'Google - Norwegian',                            engine: 'google' },

    'ru_YA':                        { name: 'Yandex - Русский',                              engine: 'yandex' },
    'ru_YA_CLOUD':                  { name: 'Yandex Cloud - Русский',                        engine: 'yandexCloud' },

    'en-US':                        { name: 'PicoTTS - Englisch US',                         engine: 'PicoTTS' },
    'en-GB':                        { name: 'PicoTTS - Englisch GB',                         engine: 'PicoTTS' },
    'de-DE':                        { name: 'PicoTTS - Deutsch',                             engine: 'PicoTTS' },
    'it-IT':                        { name: 'PicoTTS - Italiano',                            engine: 'PicoTTS' },
    'es-ES':                        { name: 'PicoTTS - Espaniol',                            engine: 'PicoTTS' },
    'fr-FR':                        { name: 'PicoTTS - Français',                            engine: 'PicoTTS' },

    'ru-RU_CLOUD_Female':           { name: 'Cloud - Русский - Татьяна',                     engine: 'cloud',        gender: 'Female', language: 'ru-RU',      ename: 'Tatyana',    ssml: true },
    'ru-RU_CLOUD_Male':             { name: 'Cloud - Русский - Максим',                      engine: 'cloud',        gender: 'Male',   language: 'ru-RU',      ename: 'Maxim',      ssml: true },
    'de-DE_CLOUD_Female':           { name: 'Cloud - Deutsch - Marlene',                     engine: 'cloud',        gender: 'Female', language: 'de-DE',      ename: 'Marlene',    ssml: true },
    'de-DE_CLOUD_Male':             { name: 'Cloud - Deutsch - Hans',                        engine: 'cloud',        gender: 'Male',   language: 'de-DE',      ename: 'Hans',       ssml: true },
    'de-DE_CLOUD_Female_Vicki':     { name: 'Cloud - Deutsch - Vicki',                       engine: 'cloud',        gender: 'Female', language: 'de-DE',      ename: 'Vicki',      ssml: true },
    'en-US_CLOUD_Female':           { name: 'Cloud - en-US - Female - Salli',                engine: 'cloud',        gender: 'Female', language: 'en-US',      ename: 'Salli',      ssml: true },
    'en-US_CLOUD_Male':             { name: 'Cloud - en-US - Male - Joey',                   engine: 'cloud',        gender: 'Male',   language: 'en-US',      ename: 'Joey',       ssml: true },
    'da-DK_CLOUD_Female':           { name: 'Cloud - da-DK - Female - Naja',                 engine: 'cloud',        gender: 'Female', language: 'da-DK',      ename: 'Naja',       ssml: true },
    'da-DK_CLOUD_Male':             { name: 'Cloud - da-DK - Male - Mads',                   engine: 'cloud',        gender: 'Male',   language: 'da-DK',      ename: 'Mads',       ssml: true },
    'en-AU_CLOUD_Female':           { name: 'Cloud - en-AU - Female - Nicole',               engine: 'cloud',        gender: 'Female', language: 'en-AU',      ename: 'Nicole',     ssml: true },
    'en-AU_CLOUD_Male':             { name: 'Cloud - en-AU - Male - Russell',                engine: 'cloud',        gender: 'Male',   language: 'en-AU',      ename: 'Russell',    ssml: true },
    'en-GB_CLOUD_Female_Amy':       { name: 'Cloud - en-GB - Female - Amy',                  engine: 'cloud',        gender: 'Female', language: 'en-GB',      ename: 'Amy',        ssml: true },
    'en-GB_CLOUD_Male':             { name: 'Cloud - en-GB - Male - Brian',                  engine: 'cloud',        gender: 'Male',   language: 'en-GB',      ename: 'Brian',      ssml: true },
    'en-GB_CLOUD_Female_Emma':      { name: 'Cloud - en-GB - Female - Emma',                 engine: 'cloud',        gender: 'Female', language: 'en-GB',      ename: 'Emma',       ssml: true },
    'en-GB-WLS_CLOUD_Female':       { name: 'Cloud - en-GB-WLS - Female - Gwyneth',          engine: 'cloud',        gender: 'Female', language: 'en-GB-WLS',  ename: 'Gwyneth',    ssml: true },
    'en-GB-WLS_CLOUD_Male':         { name: 'Cloud - en-GB-WLS - Male - Geraint',            engine: 'cloud',        gender: 'Male',   language: 'en-GB-WLS',  ename: 'Geraint',    ssml: true },
    'cy-GB_CLOUD_Female':           { name: 'Cloud - cy-GB - Female - Gwyneth',              engine: 'cloud',        gender: 'Female', language: 'cy-GB',      ename: 'Gwyneth',    ssml: true },
    'cy-GB_CLOUD_Male':             { name: 'Cloud - cy-GB - Male - Geraint',                engine: 'cloud',        gender: 'Male',   language: 'cy-GB',      ename: 'Geraint',    ssml: true },
    'en-IN_CLOUD_Female':           { name: 'Cloud - en-IN - Female - Raveena',              engine: 'cloud',        gender: 'Female', language: 'en-IN',      ename: 'Raveena',    ssml: true },
    'en-US_CLOUD_Male_Chipmunk':    { name: 'Cloud - en-US - Male - Chipmunk',               engine: 'cloud',        gender: 'Male',   language: 'en-US',      ename: 'Chipmunk',   ssml: true },
    'en-US_CLOUD_Male_Eric':        { name: 'Cloud - en-US - Male - Eric',                   engine: 'cloud',        gender: 'Male',   language: 'en-US',      ename: 'Eric',       ssml: true },
    'en-US_CLOUD_Female_Ivy':       { name: 'Cloud - en-US - Female - Ivy',                  engine: 'cloud',        gender: 'Female', language: 'en-US',      ename: 'Ivy',        ssml: true },
    'en-US_CLOUD_Female_Jennifer':  { name: 'Cloud - en-US - Female - Jennifer',             engine: 'cloud',        gender: 'Female', language: 'en-US',      ename: 'Jennifer',   ssml: true },
    'en-US_CLOUD_Male_Justin':      { name: 'Cloud - en-US - Male - Justin',                 engine: 'cloud',        gender: 'Male',   language: 'en-US',      ename: 'Justin',     ssml: true },
    'en-US_CLOUD_Female_Kendra':    { name: 'Cloud - en-US - Female - Kendra',               engine: 'cloud',        gender: 'Female', language: 'en-US',      ename: 'Kendra',     ssml: true },
    'en-US_CLOUD_Female_Kimberly':  { name: 'Cloud - en-US - Female - Kimberly',             engine: 'cloud',        gender: 'Female', language: 'en-US',      ename: 'Kimberly',   ssml: true },
    'es-ES_CLOUD_Female':           { name: 'Cloud - es-ES - Female - Conchita',             engine: 'cloud',        gender: 'Female', language: 'es-ES',      ename: 'Conchita',   ssml: true },
    'es-ES_CLOUD_Male':             { name: 'Cloud - es-ES - Male - Enrique',                engine: 'cloud',        gender: 'Male',   language: 'es-ES',      ename: 'Enrique',    ssml: true },
    'es-US_CLOUD_Female':           { name: 'Cloud - es-US - Female - Penelope',             engine: 'cloud',        gender: 'Female', language: 'es-US',      ename: 'Penelope',   ssml: true },
    'es-US_CLOUD_Male':             { name: 'Cloud - es-US - Male - Miguel',                 engine: 'cloud',        gender: 'Male',   language: 'es-US',      ename: 'Miguel',     ssml: true },
    'fr-CA_CLOUD_Female':           { name: 'Cloud - fr-CA - Female - Chantal',              engine: 'cloud',        gender: 'Female', language: 'fr-CA',      ename: 'Chantal',    ssml: true },
    'fr-FR_CLOUD_Female':           { name: 'Cloud - fr-FR - Female - Celine',               engine: 'cloud',        gender: 'Female', language: 'fr-FR',      ename: 'Celine',     ssml: true },
    'fr-FR_CLOUD_Male':             { name: 'Cloud - fr-FR - Male - Mathieu',                engine: 'cloud',        gender: 'Male',   language: 'fr-FR',      ename: 'Mathieu',    ssml: true },
    'is-IS_CLOUD_Female':           { name: 'Cloud - is-IS - Female - Dora',                 engine: 'cloud',        gender: 'Female', language: 'is-IS',      ename: 'Dora',       ssml: true },
    'is-IS_CLOUD_Male':             { name: 'Cloud - is-IS - Male - Karl',                   engine: 'cloud',        gender: 'Male',   language: 'is-IS',      ename: 'Karl',       ssml: true },
    'it-IT_CLOUD_Female':           { name: 'Cloud - it-IT - Female - Carla',                engine: 'cloud',        gender: 'Female', language: 'it-IT',      ename: 'Carla',      ssml: true },
    'it-IT_CLOUD_Male':             { name: 'Cloud - it-IT - Male - Giorgio',                engine: 'cloud',        gender: 'Male',   language: 'it-IT',      ename: 'Giorgio',    ssml: true },
    'nb-NO_CLOUD_Female':           { name: 'Cloud - nb-NO - Female - Liv',                  engine: 'cloud',        gender: 'Female', language: 'nb-NO',      ename: 'Liv',        ssml: true },
    'nl-NL_CLOUD_Female':           { name: 'Cloud - nl-NL - Female - Lotte',                engine: 'cloud',        gender: 'Female', language: 'nl-NL',      ename: 'Lotte',      ssml: true },
    'nl-NL_CLOUD_Male':             { name: 'Cloud - nl-NL - Male - Ruben',                  engine: 'cloud',        gender: 'Male',   language: 'nl-NL',      ename: 'Ruben',      ssml: true },
    'pl-PL_CLOUD_Female_Agnieszka': { name: 'Cloud - pl-PL - Female - Agnieszka',            engine: 'cloud',        gender: 'Female', language: 'pl-PL',      ename: 'Agnieszka',  ssml: true },
    'pl-PL_CLOUD_Male_Jacek':       { name: 'Cloud - pl-PL - Male - Jacek',                  engine: 'cloud',        gender: 'Male',   language: 'pl-PL',      ename: 'Jacek',      ssml: true },
    'pl-PL_CLOUD_Female_Ewa':       { name: 'Cloud - pl-PL - Female - Ewa',                  engine: 'cloud',        gender: 'Female', language: 'pl-PL',      ename: 'Ewa',        ssml: true },
    'pl-PL_CLOUD_Male_Jan':         { name: 'Cloud - pl-PL - Male - Jan',                    engine: 'cloud',        gender: 'Male',   language: 'pl-PL',      ename: 'Jan',        ssml: true },
    'pl-PL_CLOUD_Female':           { name: 'Cloud - pl-PL - Female - Maja',                 engine: 'cloud',        gender: 'Female', language: 'pl-PL',      ename: 'Maja',       ssml: true },
    'pt-BR_CLOUD_Female':           { name: 'Cloud - pt-BR - Female - Vitoria',              engine: 'cloud',        gender: 'Female', language: 'pt-BR',      ename: 'Vitoria',    ssml: true },
    'pt-BR_CLOUD_Male':             { name: 'Cloud - pt-BR - Male - Ricardo',                engine: 'cloud',        gender: 'Male',   language: 'pt-BR',      ename: 'Ricardo',    ssml: true },
    'pt-BR_CLOUD_Female_Camila':    { name: 'Cloud - pt-BR - Female - Camila',               engine: 'cloud',        gender: 'Female', language: 'pt-BR',      ename: 'Camila',     ssml: true },
    'pt-PT_CLOUD_Male':             { name: 'Cloud - pt-PT - Male - Cristiano',              engine: 'cloud',        gender: 'Male',   language: 'pt-PT',      ename: 'Cristiano',  ssml: true },
    'pt-PT_CLOUD_Female':           { name: 'Cloud - pt-PT - Female - Ines',                 engine: 'cloud',        gender: 'Female', language: 'pt-PT',      ename: 'Ines',       ssml: true },
    'ro-RO_CLOUD_Female':           { name: 'Cloud - ro-RO - Female - Carmen',               engine: 'cloud',        gender: 'Female', language: 'ro-RO',      ename: 'Carmen',     ssml: true },
    'sv-SE_CLOUD_Female':           { name: 'Cloud - sv-SE - Female - Astrid',               engine: 'cloud',        gender: 'Female', language: 'sv-SE',      ename: 'Astrid',     ssml: true },
    'tr-TR_CLOUD_Female':           { name: 'Cloud - tr-TR - Female - Filiz',                engine: 'cloud',        gender: 'Female', language: 'tr-TR',      ename: 'Filiz',      ssml: true },
    'ko-KR_CLOUD_Female':           { name: 'Cloud - ko-KR - Female - Seoyeon',              engine: 'cloud',        gender: 'Female', language: 'ko-KR',      ename: 'Seoyeon',    ssml: true },

    'ru-RU_AP_Female':              { name: 'AWS Polly - Русский - Татьяна',                 engine: 'polly',        gender: 'Female', language: 'ru-RU',      ename: 'Tatyana',    ssml: true },
    'ru-RU_AP_Male':                { name: 'AWS Polly - Русский - Максим',                  engine: 'polly',        gender: 'Male',   language: 'ru-RU',      ename: 'Maxim',      ssml: true },
    'de-DE_AP_Female':              { name: 'AWS Polly - Deutsch - Marlene',                 engine: 'polly',        gender: 'Female', language: 'de-DE',      ename: 'Marlene',    ssml: true },
    'de-DE_AP_Female_Vicki':        { name: 'AWS Polly - Deutsch - Vicki',                   engine: 'polly',        gender: 'Female', language: 'de-DE',      ename: 'Vicki',      ssml: true },
    'de-DE_AP_Male':                { name: 'AWS Polly - Deutsch - Hans',                    engine: 'polly',        gender: 'Male',   language: 'de-DE',      ename: 'Hans',       ssml: true },
    'en-US_AP_Female':              { name: 'AWS Polly - en-US - Female - Salli',            engine: 'polly',        gender: 'Female', language: 'en-US',      ename: 'Salli',      ssml: true },
    'en-US_AP_Male':                { name: 'AWS Polly - en-US - Male - Joey',               engine: 'polly',        gender: 'Male',   language: 'en-US',      ename: 'Joey',       ssml: true },
    'da-DK_AP_Female':              { name: 'AWS Polly - da-DK - Female - Naja',             engine: 'polly',        gender: 'Female', language: 'da-DK',      ename: 'Naja',       ssml: true },
    'da-DK_AP_Male':                { name: 'AWS Polly - da-DK - Male - Mads',               engine: 'polly',        gender: 'Male',   language: 'da-DK',      ename: 'Mads',       ssml: true },
    'en-AU_AP_Female':              { name: 'AWS Polly - en-AU - Female - Nicole',           engine: 'polly',        gender: 'Female', language: 'en-AU',      ename: 'Nicole',     ssml: true },
    'en-AU_AP_Male':                { name: 'AWS Polly - en-AU - Male - Russell',            engine: 'polly',        gender: 'Male',   language: 'en-AU',      ename: 'Russell',    ssml: true },
    'en-GB_AP_Female_Amy':          { name: 'AWS Polly - en-GB - Female - Amy',              engine: 'polly',        gender: 'Female', language: 'en-GB',      ename: 'Amy',        ssml: true },
    'en-GB_AP_Male':                { name: 'AWS Polly - en-GB - Male - Brian',              engine: 'polly',        gender: 'Male',   language: 'en-GB',      ename: 'Brian',      ssml: true },
    'en-GB_AP_Female_Emma':         { name: 'AWS Polly - en-GB - Female - Emma',             engine: 'polly',        gender: 'Female', language: 'en-GB',      ename: 'Emma',       ssml: true },
    'en-GB-WLS_AP_Female':          { name: 'AWS Polly - en-GB-WLS - Female - Gwyneth',      engine: 'polly',        gender: 'Female', language: 'en-GB-WLS',  ename: 'Gwyneth',    ssml: true },
    'en-GB-WLS_AP_Male':            { name: 'AWS Polly - en-GB-WLS - Male - Geraint',        engine: 'polly',        gender: 'Male',   language: 'en-GB-WLS',  ename: 'Geraint',    ssml: true },
    'cy-GB_AP_Female':              { name: 'AWS Polly - cy-GB - Female - Gwyneth',          engine: 'polly',        gender: 'Female', language: 'cy-GB',      ename: 'Gwyneth',    ssml: true },
    'cy-GB_AP_Male':                { name: 'AWS Polly - cy-GB - Male - Geraint',            engine: 'polly',        gender: 'Male',   language: 'cy-GB',      ename: 'Geraint',    ssml: true },
    'en-IN_AP_Female':              { name: 'AWS Polly - en-IN - Female - Raveena',          engine: 'polly',        gender: 'Female', language: 'en-IN',      ename: 'Raveena',    ssml: true },
    'en-US_AP_Male_Chipmunk':       { name: 'AWS Polly - en-US - Male - Chipmunk',           engine: 'polly',        gender: 'Male',   language: 'en-US',      ename: 'Chipmunk',   ssml: true },
    'en-US_AP_Male_Eric':           { name: 'AWS Polly - en-US - Male - Eric',               engine: 'polly',        gender: 'Male',   language: 'en-US',      ename: 'Eric',       ssml: true },
    'en-US_AP_Female_Ivy':          { name: 'AWS Polly - en-US - Female - Ivy',              engine: 'polly',        gender: 'Female', language: 'en-US',      ename: 'Ivy',        ssml: true },
    'en-US_AP_Female_Jennifer':     { name: 'AWS Polly - en-US - Female - Jennifer',         engine: 'polly',        gender: 'Female', language: 'en-US',      ename: 'Jennifer',   ssml: true },
    'en-US_AP_Male_Justin':         { name: 'AWS Polly - en-US - Male - Justin',             engine: 'polly',        gender: 'Male',   language: 'en-US',      ename: 'Justin',     ssml: true },
    'en-US_AP_Female_Kendra':       { name: 'AWS Polly - en-US - Female - Kendra',           engine: 'polly',        gender: 'Female', language: 'en-US',      ename: 'Kendra',     ssml: true },
    'en-US_AP_Female_Kimberly':     { name: 'AWS Polly - en-US - Female - Kimberly',         engine: 'polly',        gender: 'Female', language: 'en-US',      ename: 'Kimberly',   ssml: true },
    'es-ES_AP_Female':              { name: 'AWS Polly - es-ES - Female - Conchita',         engine: 'polly',        gender: 'Female', language: 'es-ES',      ename: 'Conchita',   ssml: true },
    'es-ES_AP_Male':                { name: 'AWS Polly - es-ES - Male - Enrique',            engine: 'polly',        gender: 'Male',   language: 'es-ES',      ename: 'Enrique',    ssml: true },
    'es-US_AP_Female':              { name: 'AWS Polly - es-US - Female - Penelope',         engine: 'polly',        gender: 'Female', language: 'es-US',      ename: 'Penelope',   ssml: true },
    'es-US_AP_Male':                { name: 'AWS Polly - es-US - Male - Miguel',             engine: 'polly',        gender: 'Male',   language: 'es-US',      ename: 'Miguel',     ssml: true },
    'fr-CA_AP_Female':              { name: 'AWS Polly - fr-CA - Female - Chantal',          engine: 'polly',        gender: 'Female', language: 'fr-CA',      ename: 'Chantal',    ssml: true },
    'fr-FR_AP_Female':              { name: 'AWS Polly - fr-FR - Female - Celine',           engine: 'polly',        gender: 'Female', language: 'fr-FR',      ename: 'Celine',     ssml: true },
    'fr-FR_AP_Male':                { name: 'AWS Polly - fr-FR - Male - Mathieu',            engine: 'polly',        gender: 'Male',   language: 'fr-FR',      ename: 'Mathieu',    ssml: true },
    'is-IS_AP_Female':              { name: 'AWS Polly - is-IS - Female - Dora',             engine: 'polly',        gender: 'Female', language: 'is-IS',      ename: 'Dora',       ssml: true },
    'is-IS_AP_Male':                { name: 'AWS Polly - is-IS - Male - Karl',               engine: 'polly',        gender: 'Male',   language: 'is-IS',      ename: 'Karl',       ssml: true },
    'it-IT_AP_Female':              { name: 'AWS Polly - it-IT - Female - Carla',            engine: 'polly',        gender: 'Female', language: 'it-IT',      ename: 'Carla',      ssml: true },
    'it-IT_AP_Male':                { name: 'AWS Polly - it-IT - Male - Giorgio',            engine: 'polly',        gender: 'Male',   language: 'it-IT',      ename: 'Giorgio',    ssml: true },
    'nb-NO_AP_Female':              { name: 'AWS Polly - nb-NO - Female - Liv',              engine: 'polly',        gender: 'Female', language: 'nb-NO',      ename: 'Liv',        ssml: true },
    'nl-NL_AP_Female':              { name: 'AWS Polly - nl-NL - Female - Lotte',            engine: 'polly',        gender: 'Female', language: 'nl-NL',      ename: 'Lotte',      ssml: true },
    'nl-NL_AP_Male':                { name: 'AWS Polly - nl-NL - Male - Ruben',              engine: 'polly',        gender: 'Male',   language: 'nl-NL',      ename: 'Ruben',      ssml: true },
    'pl-PL_AP_Female_Agnieszka':    { name: 'AWS Polly - pl-PL - Female - Agnieszka',        engine: 'polly',        gender: 'Female', language: 'pl-PL',      ename: 'Agnieszka',  ssml: true },
    'pl-PL_AP_Male_Jacek':          { name: 'AWS Polly - pl-PL - Male - Jacek',              engine: 'polly',        gender: 'Male',   language: 'pl-PL',      ename: 'Jacek',      ssml: true },
    'pl-PL_AP_Female_Ewa':          { name: 'AWS Polly - pl-PL - Female - Ewa',              engine: 'polly',        gender: 'Female', language: 'pl-PL',      ename: 'Ewa',        ssml: true },
    'pl-PL_AP_Male_Jan':            { name: 'AWS Polly - pl-PL - Male - Jan',                engine: 'polly',        gender: 'Male',   language: 'pl-PL',      ename: 'Jan',        ssml: true },
    'pl-PL_AP_Female':              { name: 'AWS Polly - pl-PL - Female - Maja',             engine: 'polly',        gender: 'Female', language: 'pl-PL',      ename: 'Maja',       ssml: true },
    'pt-BR_AP_Female':              { name: 'AWS Polly - pt-BR - Female - Vitoria',          engine: 'polly',        gender: 'Female', language: 'pt-BR',      ename: 'Vitoria',    ssml: true },
    'pt-BR_AP_Male':                { name: 'AWS Polly - pt-BR - Male - Ricardo',            engine: 'polly',        gender: 'Male',   language: 'pt-BR',      ename: 'Ricardo',    ssml: true },
    'pt-PT_AP_Male':                { name: 'AWS Polly - pt-PT - Male - Cristiano',          engine: 'polly',        gender: 'Male',   language: 'pt-PT',      ename: 'Cristiano',  ssml: true },
    'pt-PT_AP_Female':              { name: 'AWS Polly - pt-PT - Female - Ines',             engine: 'polly',        gender: 'Female', language: 'pt-PT',      ename: 'Ines',       ssml: true },
    'ro-RO_AP_Female':              { name: 'AWS Polly - ro-RO - Female - Carmen',           engine: 'polly',        gender: 'Female', language: 'ro-RO',      ename: 'Carmen',     ssml: true },
    'sv-SE_AP_Female':              { name: 'AWS Polly - sv-SE - Female - Astrid',           engine: 'polly',        gender: 'Female', language: 'sv-SE',      ename: 'Astrid',     ssml: true },
    'tr-TR_AP_Female':              { name: 'AWS Polly - tr-TR - Female - Filiz',            engine: 'polly',        gender: 'Female', language: 'tr-TR',      ename: 'Filiz',      ssml: true },
    'ko-KR_AP_Female':              { name: 'AWS Polly - ko-KR - Female - Seoyeon',          engine: 'polly',        gender: 'Female', language: 'ko-KR',      ename: 'Seoyeon',    ssml: true },

    'ar-AE_APN_Female':             { name: 'AWS Neural - Arabic (Gulf) - Hala',             engine: 'pollyNeural',  gender: 'Female', language: 'ar-AE',      ename: 'Hala',       ssml: true },
    'ca-ES_APN_Female':             { name: 'AWS Neural - Catalan - Arlet',                  engine: 'pollyNeural',  gender: 'Female', language: 'ca-ES',      ename: 'Arlet',      ssml: true },
    'yue-CN_APN_Female':            { name: 'AWS Neural - Chinese (Cantonese) - Hiujin',     engine: 'pollyNeural',  gender: 'Female', language: 'yue-CN',     ename: 'Hiujin',     ssml: true },
    'cmn-CN_APN_Female':            { name: 'AWS Neural - Chinese (Mandarin) - Zhiyu',       engine: 'pollyNeural',  gender: 'Female', language: 'cmn-CN',     ename: 'Zhiyu',      ssml: true },
    'nl-NL_APN_Female':             { name: 'AWS Neural - Dutch - Laura',                    engine: 'pollyNeural',  gender: 'Female', language: 'nl-NL',      ename: 'Laura',      ssml: true },
    'en-AU_APN_Female':             { name: 'AWS Neural - English (Australian) - Olivia',    engine: 'pollyNeural',  gender: 'Female', language: 'en-AU',      ename: 'Olivia',     ssml: true },
    'en-GB_APN_Female':             { name: 'AWS Neural - English (British) - Amy',          engine: 'pollyNeural',  gender: 'Female', language: 'en-GB',      ename: 'Amy',        ssml: true },
    'en-GB_APN_Female_Emma':        { name: 'AWS Neural - English (British) - Emma',         engine: 'pollyNeural',  gender: 'Female', language: 'en-GB',      ename: 'Emma',       ssml: true },
    'en-GB_APN_Male':               { name: 'AWS Neural - English (British) - Brian',        engine: 'pollyNeural',  gender: 'Male',   language: 'en-GB',      ename: 'Brian',      ssml: true },
    'en-GB_APN_Male_Arthur':        { name: 'AWS Neural - English (British) - Arthur',       engine: 'pollyNeural',  gender: 'Male',   language: 'en-GB',      ename: 'Arthur',     ssml: true },
    'en-IN_APN_Female':             { name: 'AWS Neural - English (Indian) - Kajal',         engine: 'pollyNeural',  gender: 'Female', language: 'en-IN',      ename: 'Kajal',      ssml: true },
    'en-NZ_APN_Female':             { name: 'AWS Neural - English (New Zealand) - Aria',     engine: 'pollyNeural',  gender: 'Female', language: 'en-NZ',      ename: 'Aria',       ssml: true },
    'en-ZA_APN_Female':             { name: 'AWS Neural - English (South African) - Ayanda', engine: 'pollyNeural',  gender: 'Female', language: 'en-ZA',      ename: 'Ayanda',     ssml: true },
    'en-US_APN_Female':             { name: 'AWS Neural - English (US) - Ivy    ',           engine: 'pollyNeural',  gender: 'Female', language: 'en-US',      ename: 'Ivy',        ssml: true },
    'en-US_APN_Female_Joanna':      { name: 'AWS Neural - English (US) - Joanna',            engine: 'pollyNeural',  gender: 'Female', language: 'en-US',      ename: 'Joanna',     ssml: true },
    'en-US_APN_Female_Kendra':      { name: 'AWS Neural - English (US) - Kendra',            engine: 'pollyNeural',  gender: 'Female', language: 'en-US',      ename: 'Kendra',     ssml: true },
    'en-US_APN_Female_Kimberl':     { name: 'AWS Neural - English (US) - Kimberl',           engine: 'pollyNeural',  gender: 'Female', language: 'en-US',      ename: 'Kimberl',    ssml: true },
    'en-US_APN_Female_Salli':       { name: 'AWS Neural - English (US) - Salli',             engine: 'pollyNeural',  gender: 'Female', language: 'en-US',      ename: 'Salli',      ssml: true },
    'en-US_APN_Male':               { name: 'AWS Neural - English (US) - Joey',              engine: 'pollyNeural',  gender: 'Male',   language: 'en-US',      ename: 'Joey',       ssml: true },
    'en-US_APN_Male_Justin':        { name: 'AWS Neural - English (US) - Justin',            engine: 'pollyNeural',  gender: 'Male',   language: 'en-US',      ename: 'Justin',     ssml: true },
    'en-US_APN_Male_Kevin':         { name: 'AWS Neural - English (US) - Kevin',             engine: 'pollyNeural',  gender: 'Male',   language: 'en-US',      ename: 'Kevin',      ssml: true },
    'en-US_APN_Male_Matthew':       { name: 'AWS Neural - English (US) - Matthew',           engine: 'pollyNeural',  gender: 'Male',   language: 'en-US',      ename: 'Matthew',    ssml: true },
    'fi-FI_APN_Female':             { name: 'AWS Neural - Finnish - Suvi',                   engine: 'pollyNeural',  gender: 'Female', language: 'fi-FI',      ename: 'Suvi',       ssml: true },
    'fr-CA_APN_Female':             { name: 'AWS Neural - French (Canadian) - Gabriell',     engine: 'pollyNeural',  gender: 'Female', language: 'fr-CA',      ename: 'Gabriell',   ssml: true },
    'fr-CA_APN_Male':               { name: 'AWS Neural - French (Canadian) - Liam',         engine: 'pollyNeural',  gender: 'Male',   language: 'fr-CA',      ename: 'Liam',       ssml: true },
    'fr-FR_APN_Female':             { name: 'AWS Neural - French - Léa',                     engine: 'pollyNeural',  gender: 'Female', language: 'fr-FR',      ename: 'Léa',        ssml: true },
    'de-DE_APN_Female':             { name: 'AWS Neural - Deutsch - Vicki',                  engine: 'pollyNeural',  gender: 'Female', language: 'de-DE',      ename: 'Vicki',      ssml: true },
    'de-DE_APN_Male':               { name: 'AWS Neural - Deutsch - Daniel',                 engine: 'pollyNeural',  gender: 'Male',   language: 'de-DE',      ename: 'Daniel',     ssml: true },
    'de-AT_APN_Female':             { name: 'AWS Neural - German (Austrian) - Hannah',       engine: 'pollyNeural',  gender: 'Female', language: 'de-AT',      ename: 'Hannah',     ssml: true },
    'hi-IN_APN_Female':             { name: 'AWS Neural - Hindi - Kajal',                    engine: 'pollyNeural',  gender: 'Female', language: 'hi-IN',      ename: 'Kajal',      ssml: true },
    'it-IT_APN_Female':             { name: 'AWS Neural - Italian - Bianca',                 engine: 'pollyNeural',  gender: 'Female', language: 'it-IT',      ename: 'Bianca',     ssml: true },
    'ja-JP_APN_Male':               { name: 'AWS Neural - Japanese - Takumi',                engine: 'pollyNeural',  gender: 'Male',   language: 'ja-JP',      ename: 'Takumi',     ssml: true },
    'ko-KR_APN_Female':             { name: 'AWS Neural - Korean - Seoyeon',                 engine: 'pollyNeural',  gender: 'Female', language: 'ko-KR',      ename: 'Seoyeon',    ssml: true },
    'nb-NO_APN_Female':             { name: 'AWS Neural - Norwegian - Ida',                  engine: 'pollyNeural',  gender: 'Female', language: 'nb-NO',      ename: 'Ida',        ssml: true },
    'pl-PL_APN_Female':             { name: 'AWS Neural - Polish - Ola',                     engine: 'pollyNeural',  gender: 'Female', language: 'pl-PL',      ename: 'Ola',        ssml: true },
    'pt-BR_APN_Female':             { name: 'AWS Neural - Portuguese (Brazilian) - Camila',  engine: 'pollyNeural',  gender: 'Female', language: 'pt-BR',      ename: 'Camila',     ssml: true },
    'pt-BR_APN_Female_Vitoria':     { name: 'AWS Neural - Portuguese (Brazilian) - Vitória', engine: 'pollyNeural',  gender: 'Female', language: 'pt-BR',      ename: 'Vitória',    ssml: true },
    'pt-PT_APN_Female':             { name: 'AWS Neural - Portuguese (European) - Inês',     engine: 'pollyNeural',  gender: 'Female', language: 'pt-PT',      ename: 'Inês',       ssml: true },
    'es-ES_APN_Female':             { name: 'AWS Neural - Spanish (European) - Lucia',       engine: 'pollyNeural',  gender: 'Female', language: 'es-ES',      ename: 'Lucia',      ssml: true },
    'es-MX_APN_Female':             { name: 'AWS Neural - Spanish (Mexican) - Mia',          engine: 'pollyNeural',  gender: 'Female', language: 'es-MX',      ename: 'Mia',        ssml: true },
    'es-US_APN_Female':             { name: 'AWS Neural - Spanish (US) - Lupe',              engine: 'pollyNeural',  gender: 'Female', language: 'es-US',      ename: 'Lupe',       ssml: true },
    'es-US_APN_Male':               { name: 'AWS Neural - Spanish (US) - Pedro',             engine: 'pollyNeural',  gender: 'Male',   language: 'es-US',      ename: 'Pedro',      ssml: true },
    'sv-SE_APN_Female':             { name: 'AWS Neural - Swedish - Elin',                   engine: 'pollyNeural',  gender: 'Female', language: 'sv-SE',      ename: 'Elin',       ssml: true },
};

if (typeof module !== 'undefined' && module.parent) {
    module.exports.sayitOptions = sayitOptions;
    module.exports.sayitEngines = sayitEngines;
}
